---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: testsite
  namespace: test
  annotations:
    fluxcd.io/automated: 'true'
spec:
  releaseName: testsite
  chart:
    git: git@gitlab.com:grdl/testflux
    path: helm/testsite
    ref: master
  values:
    image:
      repository: registry.gitlab.com/grdl/testsite
      tag: 1.0.3

